FROM --platform=linux/amd64 node:16

WORKDIR /opt/

COPY ./package.json ./
COPY ./package-lock.json ./

RUN touch .env

ENV NODE_ENV=production

RUN npm install --production

COPY . .

EXPOSE 1337

CMD ["npm", "run","start"]