name: 🚢 Release
on:
  create:
jobs:
  build:
    name: 📦 Build Image & Release

    if: ${{ startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: wwm-strapi-api
        run: >
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name}} -t
          $ECR_REGISTRY/$ECR_REPOSITORY:latest -f Dockerfile.production .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${{ github.ref_name}}

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - name: Install AWS CLI and run a command
        run: >
          echo "----Get aws cli----"

          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"

          echo "----Unzip----"

          unzip awscliv2.zip

          echo "----Install----"

          sudo ./aws/install --update 

          echo "----Check aws----"

          aws --version

          echo "----Configure----"

          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws configure set default.region ${{ secrets.AWS_REGION }}

          aws elasticbeanstalk create-application-version --application-name wwm-strapi-cms --version-label ${{ github.ref_name}} --source-bundle S3Bucket=wwm-strapi-dockerrun,S3Key=Dockerrun.aws.json

          aws elasticbeanstalk update-environment --application-name wwm-strapi-cms --environment-name wwm-strapi-cms-elb-env --version-label=${{ github.ref_name}}
